spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myz_file?serverTimezone=GMT%2B8
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 500MB
  application:
    name: fileManager
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  session:
    store-type: redis
  redis:
    password: 123456
    host: 106.12.183.82
    port: 6379
  cloud:
    alicloud:
      access-key: LTAI4GCJmr2JLxPRHkkrZ2iJ
      secret-key: GlHkNowez4qLn4jWVchdLJbdhvsLzw
      oss:
        endpoint: oss-cn-shenzhen.aliyuncs.com
        bucket: myz-files
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
